# Generated by Django 4.0.4 on 2022-05-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Created_at',
            new_name='created_at',
        ),
    ]
